name: Show Secret

on:
  workflow_dispatch:

jobs:
  show-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Print GCP Credentials
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > /tmp/creds.json
          cat /tmp/creds.json
